# Generated by Django 2.2.2 on 2019-06-17 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nombre')),
                ('title', models.CharField(max_length=500, verbose_name='Titulo')),
                ('message', models.CharField(max_length=500, verbose_name='Mensaje')),
                ('photo', models.ImageField(upload_to='section/guests', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Pie de foto')),
                ('photo', models.ImageField(upload_to='section/notices', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('lead', models.CharField(max_length=500, verbose_name='Lead Noticia')),
                ('text', models.TextField(verbose_name='Texto Noticia')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('photo', models.ManyToManyField(to='fair.Image')),
            ],
        ),
    ]
