# Generated by Django 2.2.2 on 2019-06-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='Andres', max_length=500, verbose_name='Autor'),
            preserve_default=False,
        ),
    ]
