# Generated by Django 2.2.2 on 2019-06-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0002_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('photo', models.ImageField(upload_to='section/programs', verbose_name='Foto')),
                ('text', models.TextField(verbose_name='Descripción Programa')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='footer',
            field=models.CharField(default='iMAGE', max_length=255, verbose_name='Pie de foto'),
            preserve_default=False,
        ),
    ]
