# Generated by Django 2.2.2 on 2019-06-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0003_auto_20190617_1930'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programs',
            new_name='Program',
        ),
    ]
