# Generated by Django 2.2.2 on 2019-06-17 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fair', '0005_topics'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topics',
            new_name='Topic',
        ),
    ]
